workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE=""
    artifacts:
      - ios/App/build/App.xcarchive
      - ios/App/build/logs/*.log
